name: Update Spotify Recent Tracks

on:
  push:
    branches:
      - master # or main
  pull_request:
    branches:
      - master # or main
  schedule:
    - cron: '*/10 8-16 * * *' # Runs every 10 minutes from 8 AM to 4:50 PM UTC

jobs:
  update_tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and update recent tracks
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        continue-on-error: true # added this line
        run: python .github/scripts/spotify.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: success() # Only run if the previous step succeeded
        with:
          commit_message: 'Update recent Spotify tracks'